#!/bin/bash

# Deploy schema refresh Cloud Function
# This function is triggered weekly by Cloud Scheduler to refresh embeddings

set -e

echo "=================================================="
echo "Deploying Schema Refresh Cloud Function"
echo "=================================================="

# Configuration
FUNCTION_NAME="schema-refresh-weekly"
REGION="us-central1"
RUNTIME="python311"
ENTRY_POINT="refresh_schema"
MEMORY="1GB"
TIMEOUT="540s"
# SERVICE_ACCOUNT will be auto-generated by Cloud Functions

# Load environment variables from .env file
ENV_FILE="../../.env"

if [ ! -f "$ENV_FILE" ]; then
    echo "Error: .env file not found at $ENV_FILE"
    exit 1
fi

echo "Loading environment variables from $ENV_FILE..."

# Read .env file and export variables (handling spaces in values)
while IFS='=' read -r key value; do
    # Skip comments and empty lines
    [[ $key =~ ^#.*$ ]] && continue
    [[ -z $key ]] && continue

    # Remove leading/trailing quotes from value
    value="${value%\"}"
    value="${value#\"}"

    # Export the variable
    export "$key=$value"
done < <(grep -v '^#' "$ENV_FILE" | grep -v '^$')

# Verify required environment variables
if [ -z "$GCP_PROJECT_ID" ] || [ -z "$BIGQUERY_DATASET" ]; then
    echo "Error: Missing required environment variables"
    echo "Required: GCP_PROJECT_ID, BIGQUERY_DATASET"
    exit 1
fi

echo "✓ Environment variables loaded"
echo "  Project: $GCP_PROJECT_ID"
echo "  Dataset: $BIGQUERY_DATASET"
echo "  Location: ${GCP_LOCATION:-us-central1}"

# Deploy the function
echo ""
echo "Deploying Cloud Function..."
echo "  Name: $FUNCTION_NAME"
echo "  Region: $REGION"
echo "  Memory: $MEMORY"
echo "  Timeout: $TIMEOUT"
echo ""

gcloud functions deploy $FUNCTION_NAME \
    --gen2 \
    --runtime=$RUNTIME \
    --region=$REGION \
    --source=. \
    --entry-point=$ENTRY_POINT \
    --trigger-http \
    --allow-unauthenticated \
    --memory=$MEMORY \
    --timeout=$TIMEOUT \
    --set-env-vars GCP_PROJECT_ID=$GCP_PROJECT_ID,BIGQUERY_DATASET=$BIGQUERY_DATASET,GCP_LOCATION=${GCP_LOCATION:-us-central1},SOURCE_PDF_PATH="${SOURCE_PDF_PATH:-/workspace/data/UPI Transaction Process Explained.pdf}",WEBSITE_URLS="${WEBSITE_URLS:-}" \
    --project=$GCP_PROJECT_ID

echo ""
echo "=================================================="
echo "✅ Deployment Complete!"
echo "=================================================="
echo ""
echo "Function URL:"
gcloud functions describe $FUNCTION_NAME \
    --region=$REGION \
    --project=$GCP_PROJECT_ID \
    --gen2 \
    --format='value(serviceConfig.uri)'

echo ""
echo "To test the function:"
echo "  curl https://$FUNCTION_NAME-<generated-id>-uc.a.run.app"
echo ""
echo "To view logs:"
echo "  gcloud functions logs read $FUNCTION_NAME --region=$REGION --gen2 --limit=50"
echo ""
